### ISSUE TITLE
how skip browser step?

### ISSUE THREAD

**Issue by woniuxia** [googleads/googleads-admob-api-samples#12]
url：https://github.com/googleads/googleads-admob-api-samples/tree/master/java/v1

the "Running the Examples" third step is "Complete the authorization steps on your browser."
I want to run on the server，and Want to skip this step。
Is there any other authorization method?

thanks~

**Comment by abadreldin** [comment]
Hello there,

At the moment we do not support service accounts, so it is not possible to skip the **user authentication and consent** step in the [web server application protocol](https://developers.google.com/identity/protocols/oauth2#webserver).

Thank you

**Comment by woniuxia** [comment]
thank you
