### ISSUE TITLE
how to remove pickle from admob api?

### ISSUE THREAD

**Issue by jiamo** [googleads/googleads-admob-api-samples#19]
In https://github.com/googleads/googleads-admob-api-samples/blob/master/python/v1/admob_utils.py.
Always change the pickle.
But this is not friendly for git? 

Is there a good way to remove the usage of pickle and keep the credentials continue working?

**Comment by abadreldin** [comment]
Hello there,

The token.pickle file stores the token, so it could be added to a `.gitignore` or alternatively you can store the token in another form safely for your application and update the `python/v1/admob_utils.py`.

All the best,
