### ISSUE TITLE
php/v1 composer problem

### ISSUE THREAD

**Issue by huisunlan** [googleads/googleads-admob-api-samples#21]
# composer install

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  **Problem 1**
    - Root composer.json requires google/apiclient, it could not be found in any version, there may be a typo in the package name.
  **Problem 2**
    - Root composer.json requires google/apiclient-services, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by abadreldin** [comment]
Thank you for raising this, the composer files have been updated.
